services:
  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
  auth:
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src
  mailer:
    command: npm run dev
    volumes:
      - ./mailer/src:/usr/src/app/src
  frontend:
    build: 
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend/src:/usr/src/app/src
    stdin_open: true
    tty: true
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf